using System;
using System.Collections.Generic;


namespace LicensePlate
{
    static class Jurisdiction
    {
        public static readonly Dictionary<int, string> JurisdictionLookup = new Dictionary<int, string>
        {
            {500, "USA - GOV"},
            {501, "USA - DC"},
            {502, "USA - AK"},
            {503, "USA - WA"},
            {504, "USA - OR"},
            {505, "USA - CA"},
            {506, "USA - ID"},
            {507, "USA - NV"},
            {508, "USA - MT"},
            {509, "USA - WY"},
            {510, "USA - UT"},
            {511, "USA - AZ"},
            {512, "USA - ND"},
            {513, "USA - SD"},
            {514, "USA - NE"},
            {515, "USA - CO"},
            {516, "USA - NM"},
            {517, "USA - KS"},
            {518, "USA - OK"},
            {519, "USA - TX"},
            {520, "USA - AR"},
            {521, "USA - MN"},
            {522, "USA - WI"},
            {523, "USA - IA"},
            {524, "USA - IL"},
            {525, "USA - MO"},
            {526, "USA - MI"},
            {527, "USA - IN"},
            {528, "USA - OH"},
            {529, "USA - KY"},
            {530, "USA - AL"},
            {531, "USA - TN"},
            {532, "USA - LA"},
            {533, "USA - MS"},
            {534, "USA - ME"},
            {535, "USA - VT"},
            {536, "USA - NH"},
            {537, "USA - CT"},
            {538, "USA - MA"},
            {539, "USA - RI"},
            {540, "USA - NY"},
            {541, "USA - NJ"},
            {542, "USA - DE"},
            {543, "USA - PA"},
            {544, "USA - MD"},
            {545, "USA - VA"},
            {546, "USA - WV"},
            {547, "USA - NC"},
            {548, "USA - SC"},
            {549, "USA - GA"},
            {550, "USA - FL"},
            {551, "USA - HI"},
            {552, "USA - PRI"},
            {560, "CAN - FED"},
            {561, "CAN - BC"},
            {562, "CAN - AB"},
            {563, "CAN - SK"},
            {564, "CAN - MB"},
            {565, "CAN - ON"},
            {566, "CAN - QC"},
            {567, "CAN - NS"},
            {568, "CAN - NB"},
            {569, "CAN - NL"},
            {570, "CAN - NT"},
            {571, "CAN - NU"},
            {572, "CAN - PE"},
            {573, "CAN - YT"},
        };
    }
}
